# Generated by Django 5.2.13 on 2026-04-30 02:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('document_number', models.CharField(max_length=11)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('driver_license', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'carriers',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoreCustomer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=2)),
                ('document_number', models.CharField(max_length=20)),
                ('legal_name', models.CharField(max_length=300)),
                ('trade_name', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('ubigeo', models.CharField(blank=True, max_length=6)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_customers',
                'ordering': ['legal_name'],
                'unique_together': {('document_type', 'document_number')},
            },
        ),
        migrations.CreateModel(
            name='SalesCustomerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partners.corecustomer')),
            ],
            options={
                'db_table': 'sales_customer_contacts',
            },
        ),
        migrations.CreateModel(
            name='SalesCustomerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taxpayer_status', models.CharField(blank=True, max_length=40)),
                ('taxpayer_condition', models.CharField(blank=True, max_length=20)),
                ('is_retention_agent', models.BooleanField(default=False)),
                ('payment_term_days', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('core_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to='partners.corecustomer')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles', to='inventory.pricelist')),
            ],
            options={
                'db_table': 'sales_customer_profiles',
            },
        ),
    ]
