# Generated by Django 5.2.13 on 2026-04-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_app_logo_url_and_more'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentseries',
            unique_together={('company', 'store', 'voucher_type', 'series')},
        ),
    ]
