# Generated by Django 5.2.14 on 2026-06-01 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_address_company_email_company_phone_and_more'),
        ('sales', '0003_alter_documentseries_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeansOfPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='means_of_payments', to='companies.company')),
            ],
            options={
                'db_table': 'means_of_payments',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='means_of_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='sales.meansofpayment', verbose_name='Medio de pago'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_cash', models.BooleanField(default=False, help_text='Marcar si esta condición implica cobro inmediato (no crédito). Cuando esté activo, se podrá seleccionar el Medio de Pago.', verbose_name='Es pago en efectivo')),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='companies.company')),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='sales.paymentmethod', verbose_name='Forma de pago'),
        ),
    ]
