# Generated by Django 5.2.13 on 2026-08-05 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_movement_origin_movement_reversal_of_and_more'),
        ('sales', '0005_rename_voucher_to_sales_document'),
        ('users', '0002_alter_permission_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='export_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='free_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='internal_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='inventory_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_document', to='inventory.movement'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='means_of_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_documents', to='sales.meansofpayment'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_documents', to='sales.paymentmethod'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_documents', to='inventory.pricelist'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='register_inventory_movement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_documents', to='users.employee'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='source_quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_document', to='sales.salesquotation'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_documents', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='documentseries',
            name='document_type',
            field=models.CharField(choices=[('NV', 'Nota de Venta'), ('01', 'Factura'), ('03', 'Boleta de Venta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito'), ('09', 'Guía de Remisión'), ('OV', 'Orden de Venta'), ('COT', 'Cotización')], max_length=10),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='document_type',
            field=models.CharField(choices=[('NV', 'Nota de Venta'), ('01', 'Factura'), ('03', 'Boleta de Venta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito'), ('09', 'Guía de Remisión'), ('OV', 'Orden de Venta'), ('COT', 'Cotización')], max_length=10),
        ),
    ]
