# Generated by Django 5.2.13 on 2026-04-30 02:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocumentSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=30)),
                ('format', models.CharField(default='A4', max_length=20)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('logo_url_override', models.CharField(blank=True, max_length=1000)),
                ('footer_text', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_settings', to='companies.company')),
            ],
            options={
                'db_table': 'company_document_settings',
                'unique_together': {('company', 'document_type')},
            },
        ),
    ]
