# Generated by Django 5.2.13 on 2026-04-30 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companydocumentsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='app_logo_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='pdf_logo_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='company',
            name='secondary_color',
        ),
        migrations.CreateModel(
            name='CompanyBranding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_logo_url', models.CharField(blank=True, max_length=1000)),
                ('pdf_logo_url', models.CharField(blank=True, max_length=1000)),
                ('primary_color', models.CharField(blank=True, max_length=20)),
                ('secondary_color', models.CharField(blank=True, max_length=20)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='companies.company')),
            ],
            options={
                'db_table': 'company_branding',
            },
        ),
    ]
