# Generated by Django 5.2.14 on 2026-05-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_app_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lock_movement_edits',
            field=models.BooleanField(default=True),
        ),
    ]
