# Generated by Django 5.2.14 on 2026-05-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_store_lock_movement_edits'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='companybranding',
            name='primary_color',
            field=models.CharField(blank=True, default='#066fd1', max_length=20),
        ),
        migrations.AlterField(
            model_name='companybranding',
            name='secondary_color',
            field=models.CharField(blank=True, default='#4a4a4a', max_length=20),
        ),
    ]
