from django.contrib.auth import get_user_model
from rest_framework import authentication, exceptions

from apps.api.v1.auth.tokens import decode_token


class JWTAuthentication(authentication.BaseAuthentication):
    """Authenticate users from Bearer JWT generated by apps.api.v1.auth.tokens."""

    keyword = "Bearer"

    def authenticate(self, request):
        auth_header = authentication.get_authorization_header(request).decode("utf-8")
        if not auth_header:
            return None

        parts = auth_header.split()
        if len(parts) != 2 or parts[0] != self.keyword:
            return None

        raw_token = parts[1]
        payload = decode_token(raw_token)
        if payload is None or payload.get("type") != "access":
            raise exceptions.AuthenticationFailed("Token invalido o expirado.")

        user_id = payload.get("sub")
        if not user_id:
            raise exceptions.AuthenticationFailed("Token sin subject.")

        User = get_user_model()
        try:
            user = User.objects.get(pk=user_id, is_active=True)
        except User.DoesNotExist as exc:
            raise exceptions.AuthenticationFailed("Usuario no encontrado o inactivo.") from exc

        return (user, payload)
