# Generated by Django 5.2.13 on 2026-04-30 02:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('CREDIT_NOTE', 'Nota de Crédito'), ('DEBIT_NOTE', 'Nota de Débito'), ('REMISSION_GUIDE', 'Guía de Remisión')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitido'), ('SUNAT_PENDING', 'Pendiente SUNAT'), ('SUNAT_ACCEPTED', 'Aceptado SUNAT'), ('SUNAT_REJECTED', 'Rechazado SUNAT'), ('VOIDED', 'Anulado')], default='DRAFT', max_length=20)),
                ('series', models.CharField(blank=True, max_length=10)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('issue_date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_document_number', models.CharField(max_length=20)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('igv_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('sunat_ticket', models.CharField(blank=True, max_length=120)),
                ('sunat_response_code', models.CharField(blank=True, max_length=50)),
                ('sunat_response_message', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'billing_invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='BillingInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('igv_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_igv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_invoice_lines',
            },
        ),
    ]
