from django.urls import path

from .views import (
    doctype_create,
    doctype_list,
    doctype_update,
    series_create,
    series_list,
    series_toggle,
    series_update,
    quotation_approve,
    quotation_cancel,
    quotation_copy,
    quotation_create,
    quotation_detail,
    quotation_preview,
    quotation_list,
    quotation_pdf,
    quotation_xlsx,
    quotation_reject,
    quotation_update,
    api_series_next_number,
    order_cancel,
    order_confirm,
    order_copy,
    order_create,
    order_detail,
    order_from_quot,
    order_list,
    order_pdf,
    order_update,
    voucher_cancel,
    voucher_create,
    voucher_credit,
    voucher_detail,
    voucher_from_ord,
    voucher_issue,
    voucher_list,
    voucher_pdf,
    voucher_void,
    payment_method_list,
    payment_method_create,
    payment_method_update,
    payment_method_delete,
    api_payment_method_search,
    api_payment_method_create,
    means_of_payment_list,
    means_of_payment_create,
    means_of_payment_update,
    means_of_payment_delete,
    api_means_of_payment_search,
    api_means_of_payment_create,
)

app_name = "sales"

urlpatterns = [
    # Document series
    path("series/", series_list, name="series_list"),
    path("series/new/", series_create, name="series_create"),
    path("series/<uuid:pk>/edit/", series_update, name="series_update"),
    path("series/<uuid:pk>/toggle/", series_toggle, name="series_toggle"),
    path("series/<uuid:pk>/next-number/", api_series_next_number, name="api_series_next_number"),
    # Document types
    path("document-types/", doctype_list, name="doctype_list"),
    path("document-types/new/", doctype_create, name="doctype_create"),
    path("document-types/<uuid:pk>/edit/", doctype_update, name="doctype_update"),
    # Quotations
    path("quotations/", quotation_list, name="quotation_list"),
    path("quotations/new/", quotation_create, name="quotation_create"),
    path("quotations/<uuid:pk>/", quotation_detail, name="quotation_detail"),
    path("quotations/<uuid:pk>/preview/", quotation_preview, name="quotation_preview"),
    path("quotations/<uuid:pk>/edit/", quotation_update, name="quotation_update"),
    path("quotations/<uuid:pk>/copy/", quotation_copy, name="quotation_copy"),
    path("quotations/<uuid:pk>/approve/", quotation_approve, name="quotation_approve"),
    path("quotations/<uuid:pk>/reject/", quotation_reject, name="quotation_reject"),
    path("quotations/<uuid:pk>/cancel/", quotation_cancel, name="quotation_cancel"),
    path("quotations/<uuid:pk>/pdf/", quotation_pdf, name="quotation_pdf"),
    path("quotations/xlsx/", quotation_xlsx, name="quotation_xlsx"),
    path("quotations/<uuid:pk>/create-order/", order_from_quot, name="order_from_quot"),
    # Sales orders
    path("orders/", order_list, name="order_list"),
    path("orders/new/", order_create, name="order_create"),
    path("orders/<uuid:pk>/", order_detail, name="order_detail"),
    path("orders/<uuid:pk>/edit/", order_update, name="order_update"),
    path("orders/<uuid:pk>/copy/", order_copy, name="order_copy"),
    path("orders/<uuid:pk>/confirm/", order_confirm, name="order_confirm"),
    path("orders/<uuid:pk>/cancel/", order_cancel, name="order_cancel"),
    path("orders/<uuid:pk>/pdf/", order_pdf, name="order_pdf"),
    path("orders/<uuid:pk>/issue/", voucher_from_ord, name="voucher_from_ord"),
    # Vouchers
    path("vouchers/", voucher_list, name="voucher_list"),
    path("vouchers/new/", voucher_create, name="voucher_create"),
    path("vouchers/<uuid:pk>/", voucher_detail, name="voucher_detail"),
    path("vouchers/<uuid:pk>/issue/", voucher_issue, name="voucher_issue"),
    path("vouchers/<uuid:pk>/void/", voucher_void, name="voucher_void"),
    path("vouchers/<uuid:pk>/cancel/", voucher_cancel, name="voucher_cancel"),
    path("vouchers/<uuid:pk>/credit-note/", voucher_credit, name="voucher_credit"),
    path("vouchers/<uuid:pk>/pdf/", voucher_pdf, name="voucher_pdf"),
    # Payment methods (Formas de pago: Contado, Crédito)
    path("payment-methods/", payment_method_list, name="payment_method_list"),
    path("payment-methods/new/", payment_method_create, name="payment_method_create"),
    path("payment-methods/<uuid:pk>/edit/", payment_method_update, name="payment_method_update"),
    path("payment-methods/<uuid:pk>/delete/", payment_method_delete, name="payment_method_delete"),
    path("api/payment-methods/search/", api_payment_method_search, name="api_payment_method_search"),
    path("api/payment-methods/create/", api_payment_method_create, name="api_payment_method_create"),
    # Means of payment (Medios de pago: Efectivo, Yape, Plin)
    path("means-of-payments/", means_of_payment_list, name="means_of_payment_list"),
    path("means-of-payments/new/", means_of_payment_create, name="means_of_payment_create"),
    path("means-of-payments/<uuid:pk>/edit/", means_of_payment_update, name="means_of_payment_update"),
    path("means-of-payments/<uuid:pk>/delete/", means_of_payment_delete, name="means_of_payment_delete"),
    path("api/means-of-payments/search/", api_means_of_payment_search, name="api_means_of_payment_search"),
    path("api/means-of-payments/create/", api_means_of_payment_create, name="api_means_of_payment_create"),
]
