# Generated by Django 5.2.14 on 2026-05-23 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_store_lock_movement_edits'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['module', 'action_name']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='permission',
            name='action_name',
            field=models.CharField(blank=True, choices=[('read', 'Leer'), ('manage', 'Gestionar'), ('authorize', 'Autorizar')], max_length=30),
        ),
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.CharField(blank=True, help_text='Ej: inventory.products', max_length=100),
        ),
        migrations.AddField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='UserOperationalFlags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_operation_admin', models.BooleanField(default=False, verbose_name='Administrador Módulo Operaciones')),
                ('ignore_notification_emails', models.BooleanField(default=False, verbose_name='No recibir notificaciones por correo')),
                ('is_seller_profile', models.BooleanField(default=False, verbose_name='Perfil Vendedor')),
                ('restricted_shop_access', models.BooleanField(default=False, verbose_name='Acceso Restringido Compras')),
                ('can_authorize_purchase_request', models.BooleanField(default=False, verbose_name='Autorizar cambio estados SC')), # Nuevo flag para autorizar cambios de estado en solicitudes de compra trabajo para cuadno hay ordenes de compra
                ('can_close_purchase_order', models.BooleanField(default=False, verbose_name='Activar para cerrar OC')),
                ('restrict_unaccepted_po_pdf', models.BooleanField(default=False, verbose_name='Restringir PDF de OC sin aceptar')),
                ('can_close_sale_order', models.BooleanField(default=False, verbose_name='Activar para cerrar OV')),
                ('see_all_price_lists', models.BooleanField(default=False, verbose_name='Ver todas las listas de precio en ventas')),
                ('can_close_credits', models.BooleanField(default=False, verbose_name='Activar para cerrar Créditos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_operational_flags', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flags Operativos de Usuario',
                'verbose_name_plural': 'Flags Operativos de Usuarios',
                'db_table': 'user_operational_flags',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
