# Generated by Django 5.2.13 on 2026-04-30 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('inventory', '0002_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movement',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='partners.corecustomer'),
        ),
        migrations.AddField(
            model_name='movement',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='partners.documenttype'),
        ),
        migrations.AddField(
            model_name='movement',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='companies.store'),
        ),
        migrations.AddField(
            model_name='movement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='partners.supplier'),
        ),
        migrations.AddField(
            model_name='movementdetail',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.movement'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='movementdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_details', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='inventory.pricelist'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockbywarehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='storeproductconfig',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_configs', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='storeproductconfig',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_configs', to='companies.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.store'),
        ),
        migrations.AddField(
            model_name='stockbywarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='movement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='movement',
            name='warehouse_dest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='movement',
            name='warehouse_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'price_list')},
        ),
        migrations.AlterUniqueTogether(
            name='storeproductconfig',
            unique_together={('store', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='stockbywarehouse',
            unique_together={('product', 'warehouse')},
        ),
    ]
