# Generated by Django 5.2.14 on 2026-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
