# Generated by Django 5.2.14 on 2026-05-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_company_scoped_masters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['-is_default', 'name']},
        ),
        migrations.AddField(
            model_name='pricelist',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Lista por defecto'),
        ),
    ]
