# Generated by Django 5.2.13 on 2026-08-05 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_pricelist_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='origin',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SALE', 'Venta'), ('SALE_REVERSAL', 'Reversión de venta')], default='MANUAL', max_length=30),
        ),
        migrations.AddField(
            model_name='movement',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='inventory.movement'),
        ),
        migrations.AddField(
            model_name='product',
            name='tracks_inventory',
            field=models.BooleanField(default=True, help_text='Desmarcar para servicios u otros conceptos que no modifican stock.'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='allow_negative_stock',
            field=models.BooleanField(default=False),
        ),
    ]
