# Generated by Django 5.2.14 on 2026-08-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_units_and_movement_uom'),
        ('inventory', '0011_product_additional_image_keys'),
    ]

    operations = [
    ]
