# Generated by Django 5.2 on 2026-08-28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_company_address_company_email_company_phone_and_more"),
        ("inventory", "0012_merge_20260827_1744"),
        ("partners", "0004_documenttype_commercial_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("supplier_code", models.CharField(blank=True, max_length=100)),
                ("supplier_product_name", models.CharField(blank=True, max_length=500)),
                ("supplier_description", models.TextField(blank=True)),
                ("purchase_price", models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ("is_preferred", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_suppliers", to="companies.company")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="supplier_relations", to="inventory.product")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_relations", to="partners.supplier")),
            ],
            options={
                "db_table": "product_suppliers",
                "ordering": ["-is_preferred", "supplier__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="productsupplier",
            constraint=models.UniqueConstraint(fields=("product", "supplier"), name="uniq_product_supplier"),
        ),
        migrations.AddConstraint(
            model_name="productsupplier",
            constraint=models.UniqueConstraint(condition=~models.Q(supplier_code=""), fields=("company", "supplier", "supplier_code"), name="uniq_supplier_product_code_nonempty"),
        ),
        migrations.AddConstraint(
            model_name="productsupplier",
            constraint=models.UniqueConstraint(condition=models.Q(is_preferred=True), fields=("product",), name="uniq_preferred_supplier_per_product"),
        ),
        migrations.AddConstraint(
            model_name="productsupplier",
            constraint=models.CheckConstraint(condition=models.Q(active=True) | models.Q(is_preferred=False), name="product_supplier_preferred_requires_active"),
        ),
    ]
