# Generated by Django 5.2.13 on 2026-09-01 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_repair_productunit_default_flags'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='purchase_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='purchases.purchasedocument'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='origin',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SALE', 'Venta'), ('SALE_REVERSAL', 'Reversión de venta'), ('PURCHASE', 'Compra'), ('PURCHASE_REVERSAL', 'Reversión de compra')], default='MANUAL', max_length=30),
        ),
    ]
