# Generated by Django 5.2.13 on 2026-09-01 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_movement_purchase_document_alter_movement_origin'),
        ('purchases', '0005_purchasedocumentline_purchase_order_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='purchase_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='purchases.purchasereceipt'),
        ),
    ]
