from django.urls import path

from .views import (
    CashMovementAPIView,
    CashSessionCloseAPIView,
    CashSessionOpenAPIView,
    CashSessionSummaryAPIView,
    ConsolidatedInvoiceAPIView,
    CreditCollectionAPIView,
    InvoiceRequestAPIView,
    InvoiceableTicketListAPIView,
    PosBootstrapAPIView,
    PosCheckoutAPIView,
    PosDraftAPIView,
    PosDraftCancelAPIView,
    PosCustomerCreateAPIView,
    PosProductSearchAPIView,
    PosProductCommercialAPIView,
    PosProductCreateAPIView,
    RecentPosTransactionsAPIView,
    PosTransactionDetailAPIView,
    PosTransactionDebitNoteAPIView,
    PosTransactionReprintAPIView,
    PosTransactionReturnAPIView,
    PosTransactionVoidAPIView,
)


urlpatterns = [
    path("bootstrap/", PosBootstrapAPIView.as_view(), name="api_v1_pos_bootstrap"),
    path("products/", PosProductSearchAPIView.as_view(), name="api_v1_pos_products"),
    path("products/create/", PosProductCreateAPIView.as_view(), name="api_v1_pos_product_create"),
    path("products/<uuid:product_id>/commercial/", PosProductCommercialAPIView.as_view(), name="api_v1_pos_product_commercial"),
    path("sessions/open/", CashSessionOpenAPIView.as_view(), name="api_v1_pos_session_open"),
    path("sessions/<uuid:session_id>/movements/", CashMovementAPIView.as_view(), name="api_v1_pos_cash_movement"),
    path("sessions/<uuid:session_id>/summary/", CashSessionSummaryAPIView.as_view(), name="api_v1_pos_cash_summary"),
    path("sessions/<uuid:session_id>/close/", CashSessionCloseAPIView.as_view(), name="api_v1_pos_session_close"),
    path("sales/checkout/", PosCheckoutAPIView.as_view(), name="api_v1_pos_checkout"),
    path("collections/", CreditCollectionAPIView.as_view(), name="api_v1_pos_collections"),
    path("sales/drafts/", PosDraftAPIView.as_view(), name="api_v1_pos_draft"),
    path("sales/<uuid:transaction_id>/cancel-draft/", PosDraftCancelAPIView.as_view(), name="api_v1_pos_draft_cancel"),
    path("sales/<uuid:transaction_id>/", PosTransactionDetailAPIView.as_view(), name="api_v1_pos_transaction_detail"),
    path("sales/recent/", RecentPosTransactionsAPIView.as_view(), name="api_v1_pos_recent_transactions"),
    path("sales/<uuid:transaction_id>/reprint/", PosTransactionReprintAPIView.as_view(), name="api_v1_pos_transaction_reprint"),
    path("sales/<uuid:transaction_id>/return/", PosTransactionReturnAPIView.as_view(), name="api_v1_pos_transaction_return"),
    path("sales/<uuid:transaction_id>/debit-note/", PosTransactionDebitNoteAPIView.as_view(), name="api_v1_pos_transaction_debit_note"),
    path("sales/<uuid:transaction_id>/void/", PosTransactionVoidAPIView.as_view(), name="api_v1_pos_transaction_void"),
    path("invoiceable-tickets/", InvoiceableTicketListAPIView.as_view(), name="api_v1_pos_invoiceable_tickets"),
    path("invoice-requests/", InvoiceRequestAPIView.as_view(), name="api_v1_pos_invoice_request"),
    path("consolidated-invoices/", ConsolidatedInvoiceAPIView.as_view(), name="api_v1_pos_consolidated_invoice"),
    path("customers/", PosCustomerCreateAPIView.as_view(), name="api_v1_pos_customer_create"),
]
