# Generated by Django 5.2.13 on 2026-08-31 23:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_company_address_company_email_company_phone_and_more'),
        ('inventory', '0014_repair_productunit_default_flags'),
        ('partners', '0004_documenttype_commercial_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_status', models.CharField(choices=[('DRAFT', 'Borrador'), ('REGISTERED', 'Registrado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'No pagado'), ('PARTIALLY_PAID', 'Parcialmente pagado'), ('PAID', 'Pagado')], default='UNPAID', max_length=20)),
                ('supplier_document_number', models.CharField(max_length=20)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_address', models.CharField(blank=True, max_length=500)),
                ('series', models.CharField(blank=True, max_length=20)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('exempt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unaffected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igv_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('register_inventory_movement', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('internal_reference', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_documents', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_documents', to='partners.documenttype')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_documents', to='companies.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_documents', to='partners.supplier')),
            ],
            options={
                'db_table': 'purchase_documents',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseDocumentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_code', models.CharField(max_length=10)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('stock_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_type', models.CharField(choices=[('10', 'Gravado IGV'), ('20', 'Exonerado'), ('30', 'Inafecto'), ('40', 'Importacion')], default='10', max_length=5)),
                ('igv_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igv_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('update_purchase_price', models.BooleanField(default=True)),
                ('memo', models.CharField(blank=True, max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_document_lines', to='inventory.product')),
                ('purchase_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchasedocument')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_document_lines', to='inventory.unit')),
            ],
            options={
                'db_table': 'purchase_document_lines',
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchasedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'supplier', 'document_type', 'series', 'number'), name='uniq_supplier_purchase_document_number'),
        ),
        migrations.AddConstraint(
            model_name='purchasedocument',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='purchase_document_exchange_rate_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasedocumentline',
            constraint=models.UniqueConstraint(fields=('purchase_document', 'position'), name='uniq_purchase_document_line_position'),
        ),
        migrations.AddConstraint(
            model_name='purchasedocumentline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_document_line_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasedocumentline',
            constraint=models.CheckConstraint(condition=models.Q(('conversion_factor__gt', 0)), name='purchase_document_line_factor_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasedocumentline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_document_line_price_gte_zero'),
        ),
    ]
