# Generated by Django 5.2.13 on 2026-09-01 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_address_company_email_company_phone_and_more'),
        ('inventory', '0015_movement_purchase_document_alter_movement_origin'),
        ('purchases', '0002_purchasedocument_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_document_lines', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='purchasedocumentline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_document_lines', to='inventory.unit'),
        ),
        migrations.CreateModel(
            name='PurchaseCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_categories', to='companies.company')),
            ],
            options={
                'db_table': 'purchase_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='purchase_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='purchases.purchasecategory'),
        ),
        migrations.AddConstraint(
            model_name='purchasedocumentline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('purchase_category__isnull', True)), models.Q(('product__isnull', True), ('purchase_category__isnull', False)), _connector='OR'), name='purchase_line_product_xor_category'),
        ),
        migrations.AddConstraint(
            model_name='purchasecategory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_company_purchase_category_code'),
        ),
    ]
