# Generated by Django 5.2.13 on 2026-09-01 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_movement_purchase_document_alter_movement_origin'),
        ('purchases', '0004_purchaseorder_purchasedocument_purchase_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocumentline',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='purchases.purchaseorderline'),
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=30)),
                ('receipt_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('REGISTERED', 'Registrada'), ('CANCELLED', 'Cancelada')], default='REGISTERED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchases.purchaseorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'purchase_receipts',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchases.purchaseorderline')),
                ('purchase_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchasereceipt')),
            ],
            options={
                'db_table': 'purchase_receipt_lines',
            },
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'receipt_number'), name='uniq_purchase_order_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceiptline',
            constraint=models.UniqueConstraint(fields=('purchase_receipt', 'purchase_order_line'), name='uniq_receipt_order_line'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_receipt_line_quantity_gt_zero'),
        ),
    ]
