# Generated by Django 5.2.13 on 2026-09-01 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_existing_document_installments(apps, schema_editor):
    PurchaseDocument = apps.get_model('purchases', 'PurchaseDocument')
    Installment = apps.get_model('purchases', 'PurchasePayableInstallment')
    installments = [
        Installment(
            purchase_document=document,
            sequence=1,
            due_date=document.due_date or document.issue_date,
            amount=document.total,
        )
        for document in PurchaseDocument.objects.filter(
            document_status='REGISTERED', total__gt=0
        ).iterator()
    ]
    Installment.objects.bulk_create(installments)


def remove_existing_document_installments(apps, schema_editor):
    apps.get_model('purchases', 'PurchasePayableInstallment').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_address_company_email_company_phone_and_more'),
        ('partners', '0004_documenttype_commercial_fields'),
        ('purchases', '0005_purchasedocumentline_purchase_order_line_and_more'),
        ('sales', '0010_sale_lines_uom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePayableInstallment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purchase_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='purchases.purchasedocument')),
            ],
            options={
                'db_table': 'purchase_payable_installments',
                'ordering': ('due_date', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=30)),
                ('payment_date', models.DateTimeField()),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registrado'), ('CANCELLED', 'Anulado')], default='REGISTERED', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_created', to=settings.AUTH_USER_MODEL)),
                ('means_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='sales.meansofpayment')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='companies.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='partners.supplier')),
            ],
            options={
                'db_table': 'supplier_payments',
                'ordering': ('-payment_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='purchases.purchasepayableinstallment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='purchases.supplierpayment')),
            ],
            options={
                'db_table': 'supplier_payment_allocations',
            },
        ),
        migrations.AddConstraint(
            model_name='purchasepayableinstallment',
            constraint=models.UniqueConstraint(fields=('purchase_document', 'sequence'), name='uniq_document_installment_sequence'),
        ),
        migrations.AddConstraint(
            model_name='purchasepayableinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='purchase_installment_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.UniqueConstraint(fields=('company', 'payment_number'), name='uniq_company_supplier_payment_number'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_payment_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='supplier_payment_exchange_rate_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'installment'), name='uniq_payment_installment_allocation'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_payment_allocation_amount_gt_zero'),
        ),
        migrations.RunPython(
            create_existing_document_installments,
            remove_existing_document_installments,
        ),
    ]
