# Generated by Django 5.2.13 on 2026-09-01 22:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchasepayableinstallment_supplierpayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLandedCost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocation_method', models.CharField(choices=[('VALUE', 'Por valor'), ('QUANTITY', 'Por cantidad base'), ('MANUAL', 'Manual')], default='VALUE', max_length=20)),
                ('status', models.CharField(choices=[('ALLOCATED', 'Distribuido'), ('CANCELLED', 'Anulado')], default='ALLOCATED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_landed_costs_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_costs', to='purchases.purchasedocument')),
            ],
            options={
                'db_table': 'purchase_landed_costs',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseLandedCostAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('landed_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='purchases.purchaselandedcost')),
                ('purchase_document_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_allocations', to='purchases.purchasedocumentline')),
            ],
            options={
                'db_table': 'purchase_landed_cost_allocations',
            },
        ),
        migrations.AddConstraint(
            model_name='purchaselandedcost',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='purchase_landed_cost_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaselandedcostallocation',
            constraint=models.UniqueConstraint(fields=('landed_cost', 'purchase_document_line'), name='uniq_landed_cost_document_line'),
        ),
        migrations.AddConstraint(
            model_name='purchaselandedcostallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='purchase_landed_allocation_amount_gte_zero'),
        ),
    ]
