# Generated by Django 5.2.13 on 2026-09-24 22:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_deduplicate_company_accesses'),
        ('inventory', '0019_movement_sales_document'),
        ('pos', '0004_pos_credit_payment_condition'),
        ('sales', '0015_salesdocument_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosReturn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='COMPLETED', max_length=15)),
                ('idempotency_key', models.UUIDField()),
                ('reason_code', models.CharField(blank=True, max_length=5)),
                ('reason', models.CharField(max_length=500)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.cashsession')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_returns', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos_returns', to=settings.AUTH_USER_MODEL)),
                ('credit_note', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_return', to='sales.salesdocument')),
                ('inventory_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_return', to='inventory.movement')),
                ('original_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.postransaction')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.posregister')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_returns', to='companies.store')),
            ],
            options={
                'db_table': 'pos_returns',
                'ordering': ('-completed_at',),
            },
        ),
        migrations.CreateModel(
            name='PosRefundPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('operation_reference', models.CharField(blank=True, max_length=120)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_payments', to='pos.cashsession')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos_refund_payments', to=settings.AUTH_USER_MODEL)),
                ('means_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_refund_payments', to='sales.meansofpayment')),
                ('pos_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_payments', to='pos.posreturn')),
            ],
            options={
                'db_table': 'pos_refund_payments',
            },
        ),
        migrations.CreateModel(
            name='PosReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('stock_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('original_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_return_lines', to='sales.salesdocumentline')),
                ('pos_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.posreturn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_return_lines', to='inventory.product')),
            ],
            options={
                'db_table': 'pos_return_lines',
            },
        ),
        migrations.AddConstraint(
            model_name='posreturn',
            constraint=models.UniqueConstraint(fields=('company', 'register', 'idempotency_key'), name='uniq_pos_return_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='posreturn',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='pos_return_total_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='posrefundpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='pos_refund_payment_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='posreturnline',
            constraint=models.UniqueConstraint(fields=('pos_return', 'original_line'), name='uniq_pos_return_original_line'),
        ),
        migrations.AddConstraint(
            model_name='posreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='pos_return_line_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='posreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='pos_return_line_stock_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='posreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='pos_return_line_total_gt_zero'),
        ),
    ]
