# Generated by Django 5.2.13 on 2026-09-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_posreturn_posrefundpayment_posreturnline_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashtenderdeclaration',
            name='cash_tender_expected_gte_zero',
        ),
        migrations.RemoveConstraint(
            model_name='cashtenderdeclaration',
            name='cash_tender_counted_gte_zero',
        ),
    ]
